<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>banner_5mb_alert</name>
   <tag></tag>
   <elementGuidId>724ad59f-7370-466c-a3df-5f0796062941</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(text(),'5MB以下のファイルを選択して下さい')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(text(),'5MB以下のファイルを選択して下さい')]</value>
   </webElementProperties>
</WebElementEntity>
