<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Content_Quiz_Present</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>c5ef6209-9324-44a8-acc2-7af3927ee29e</testSuiteGuid>
   <testCaseLink>
      <guid>dc26464a-4f0b-4844-8d1c-cef1117a6e7a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Content_management/Content_Create_Edit</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>56bc0663-1224-4f76-b4b5-0114968b852a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Content_management/Content_list</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c1f5d4ff-a9b0-4eac-9ec8-2c27612c1171</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2fe5cd25-a066-4c1c-b011-b512e48d06f4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>17f6bf52-5b2f-4594-8daf-5637d004e562</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>46847ace-4962-4589-98b9-31ce57745807</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>feb180ce-9418-4772-b09f-091b13aeb918</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aa1b929f-3a16-4876-a5a3-781f1bfd76a2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>95792c85-1ff5-4e39-be1b-5c6dd7c5d1cd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Quiz_management/Quiz_Create_Edit</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>a5c91794-b88b-4fe5-8d03-8ad9536f7125</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Quiz_management/Quiz_Edit</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>7f3f34e7-e868-47e5-9010-ddbcedf3d1d9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Quiz_management/Quiz_List</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c19c3437-12bb-4e4e-8dc6-00c41225bf83</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>23b9852f-59db-4b7c-8ad2-4a169772a011</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a47f7661-700d-4ce6-bbe0-e6faf95e7406</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2a47e08f-d278-4c1a-8191-c4301942f9be</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d641aa44-51ab-4dba-aac7-d6e4532961ac</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Present_management/Present_Create</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>60c45efc-e3cd-4481-850b-60fc5f5f35bf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Present_management/Present_edit</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>583ec79b-367a-482f-b4c9-e2fa4b086cd0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>744f4521-963d-4110-8648-005dc7126a63</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f2c244c7-be3b-4097-9263-00d4a286c95b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dd1f1449-4700-4332-bf00-c4a7ddfffbe1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0e755a32-9ada-4ed0-bf94-3f4b0c717016</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>749e0111-0be2-4682-9b90-1aafea4b4ca1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Present_management/Present_list</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fb0c064a-5130-4d49-a5a8-c5ed74664064</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0f9b56e8-0a44-4109-b3e0-a4e5cfb7cb8b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6ce3f422-97fb-4a95-84ba-4ee0205e3324</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3c563b48-5104-4771-8858-e5a4864de5c2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2f0a1d8e-5e27-4fa2-9920-30307b6c630e</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
