<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Product_Coupon_EpisodeManagement</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>1df214d7-f2bb-441d-acf9-0e117d3c30a5</testSuiteGuid>
   <testCaseLink>
      <guid>b45896d2-f56c-46e1-b2bf-e6c0ce1152ed</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Product_Management/Product_Create</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fdbdda7e-9755-4093-b5a2-45a3706dacae</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fbf5bcaa-3b83-4540-ab09-72cb4d305370</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>36bfa620-e68f-4633-a1d4-da4953fd9336</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>47b21def-7003-43c6-a3e3-3e3e017108cd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>16c55a21-4f03-417a-9cd4-dd6c2323e11c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f90cf67d-7f10-43c0-a6c5-b732363a5d01</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8d2b2e2b-647f-48f5-b8e6-f733a0c5c547</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Product_Management/Product_Edit</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d4198e90-5bc0-4140-8a82-cb995b2ca65b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2a8cccf4-2e85-45af-8029-e7d3f27e8e41</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e87ee1f2-0145-4b98-8888-53b023d21b3f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>189106d6-7a27-4395-bc07-dc5dc9ab3894</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5ed28053-6c1e-47f8-a0bb-a44033326d4e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2720a8c1-2445-49fa-95d2-5c275173e31a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c6ade099-dfee-4d9f-bc31-007abe6fdcd1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Product_Management/Product_List</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9c0effde-c34f-491d-aec2-62a5b5350128</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bf848578-f676-4bce-a689-0e1d4243d17e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>70e8054c-7311-40fa-a487-2d87abf0b1a1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8a74de09-63d7-4931-9cf4-2136f98739a7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c951a4d1-328d-4963-b4e0-9efcf0de14fd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4c29e6be-7d69-408e-8b5e-b4056fa627d1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7e0bae71-9e1b-481f-9c0b-ef6ed1d009c6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2ef4154f-b652-47da-b7d4-5a98ad3126d1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6a559e48-8063-4bd0-94f7-104397309907</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Coupon_List/Coupon_Create</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>5cef4e7a-8866-44b7-be76-21ed39415179</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Coupon_List/Coupon_List</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2c3026bc-ccda-4876-a0a4-7793e58d8500</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ca399a0a-4765-43d4-98f0-dab8bde86583</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>94fa8404-4933-4ad2-9408-a0b8f9432fe8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c4de8b7f-6226-463d-a2d1-1e2830d1a105</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>80fa2e3e-b99a-4a0b-a565-0e36e973d08f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>30efe50f-55fd-4e51-81c5-996175d59e6a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9b9da8c5-aa92-4c3a-a42b-85df2b319d46</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>480e8292-376e-4923-a456-ee9d8225689b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7e4ea138-2a83-4a06-8480-39a8c9929513</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Quiz_management/Quiz_Create_Edit</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>7918ec88-599f-431b-a174-8530c4a0be7f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Quiz_management/Quiz_Edit</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>f86a3838-b3fc-4062-b100-878b28847d5c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Quiz_management/Quiz_List</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c19c3437-12bb-4e4e-8dc6-00c41225bf83</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>23b9852f-59db-4b7c-8ad2-4a169772a011</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a47f7661-700d-4ce6-bbe0-e6faf95e7406</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2a47e08f-d278-4c1a-8191-c4301942f9be</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
