<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ans_start</name>
   <tag></tag>
   <elementGuidId>9008a87e-91cd-43bc-8cbd-e1deef0f8fb1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//label[contains(text(),'回答開始時間(時:分:秒)(バナー表示開始時間)')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//label[contains(text(),'回答開始時間(時:分:秒)(バナー表示開始時間)')]</value>
   </webElementProperties>
</WebElementEntity>
