<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>content_name</name>
   <tag></tag>
   <elementGuidId>622c7a60-5837-4b63-bc68-f08a7406311c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//th['_ngcontent-ucx-c94'][contains(text(),'コンテンツ名')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//th['_ngcontent-ucx-c94'][contains(text(),'コンテンツ名')]</value>
   </webElementProperties>
</WebElementEntity>
