<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>content_management_button</name>
   <tag></tag>
   <elementGuidId>140343b1-c986-427c-9d30-1e3a3155f3d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//app-side-bar//li[4]//a[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//app-side-bar//li[4]//a[1]</value>
   </webElementProperties>
</WebElementEntity>
