<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>edit_column</name>
   <tag></tag>
   <elementGuidId>3108b1bb-4fb3-4f9c-83c7-775bad55af3e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//th[7]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//th[7]</value>
   </webElementProperties>
</WebElementEntity>
