<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>representation</name>
   <tag></tag>
   <elementGuidId>0f6e410e-f505-4571-abc4-94c050bb1d07</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//th[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//th[5]</value>
   </webElementProperties>
</WebElementEntity>
