<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>header</name>
   <tag></tag>
   <elementGuidId>5bb7eb5f-1355-4891-b6b3-1cc94b267dfb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//body/app-root[1]/app-dashboard-layout[1]/main[1]/app-edit[1]/section[1]/h4[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//body/app-root[1]/app-dashboard-layout[1]/main[1]/app-edit[1]/section[1]/h4[1]</value>
   </webElementProperties>
</WebElementEntity>
