<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>5mb_alrt</name>
   <tag></tag>
   <elementGuidId>fd373322-8fab-4de8-aef4-8ce249de8b80</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(text(),'5MB以下のファイルを選択して下さい')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(text(),'5MB以下のファイルを選択して下さい')]</value>
   </webElementProperties>
</WebElementEntity>
