<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>announce_alrt</name>
   <tag></tag>
   <elementGuidId>951ee3b6-4275-47a0-960a-3d34fecaacfe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//body/app-root[1]/app-dashboard-layout[1]/main[1]/app-create[1]/section[1]/div[1]/div[2]/form[1]/div[9]/app-validation-message[1]/div[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//body/app-root[1]/app-dashboard-layout[1]/main[1]/app-create[1]/section[1]/div[1]/div[2]/form[1]/div[9]/app-validation-message[1]/div[1]</value>
   </webElementProperties>
</WebElementEntity>
