<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>add</name>
   <tag></tag>
   <elementGuidId>37abe680-17f3-492e-ba8f-76a16be0a18d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//body/app-root[1]/app-dashboard-layout[1]/main[1]/app-list[1]/section[1]/h4[1]/a[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//body/app-root[1]/app-dashboard-layout[1]/main[1]/app-list[1]/section[1]/h4[1]/a[1]</value>
   </webElementProperties>
</WebElementEntity>
