<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>cat_dropdown</name>
   <tag></tag>
   <elementGuidId>2395308e-f046-49c1-b4d4-64f5cb404061</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[6]//select[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[6]//select[1]</value>
   </webElementProperties>
</WebElementEntity>
