<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>content_video</name>
   <tag></tag>
   <elementGuidId>538b460b-23b5-430a-bfd6-8ce417923391</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[5]//label[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[5]//label[1]</value>
   </webElementProperties>
</WebElementEntity>
