<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_content_id</name>
   <tag></tag>
   <elementGuidId>d5310c45-2864-4cad-b29f-d4e26467db25</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//body/app-root/app-dashboard-layout/main/app-edit/section/div/div/form/div[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//body/app-root/app-dashboard-layout/main/app-edit/section/div/div/form/div[1]</value>
   </webElementProperties>
</WebElementEntity>
