<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>item_ID</name>
   <tag></tag>
   <elementGuidId>e4d3ebd3-8223-456a-97a0-ea9fddf65fdb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//th[contains(text(),'アイテムID')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//th[contains(text(),'アイテムID')]</value>
   </webElementProperties>
</WebElementEntity>
