<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>edit_table</name>
   <tag></tag>
   <elementGuidId>eccb4138-1f4f-47d1-8346-210a71915ae1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//th[6]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//th[6]</value>
   </webElementProperties>
</WebElementEntity>
