<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>item_id</name>
   <tag></tag>
   <elementGuidId>5c9ae75e-f93c-4baf-bbbd-63918beb45ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//th['_ngcontent-uer-c107'][contains(text(),'アイテムID')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//th['_ngcontent-uer-c107'][contains(text(),'アイテムID')]</value>
   </webElementProperties>
</WebElementEntity>
