<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>status</name>
   <tag></tag>
   <elementGuidId>c008288b-cfcb-4cf0-a99e-176abc197343</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[12]//label[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[12]//label[1]</value>
   </webElementProperties>
</WebElementEntity>
