<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>bulk</name>
   <tag></tag>
   <elementGuidId>b973b784-005a-4720-8273-1f6fc9737855</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//app-bulk-upload//h5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//app-bulk-upload//h5</value>
   </webElementProperties>
</WebElementEntity>
