<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>bulk_cancel</name>
   <tag></tag>
   <elementGuidId>91dff965-acee-4760-a6c9-6968b063b5bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//body//app-bulk-upload//button[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//body//app-bulk-upload//button[2]</value>
   </webElementProperties>
</WebElementEntity>
