<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>update_success</name>
   <tag></tag>
   <elementGuidId>a02ae510-8ca7-4409-af4f-2802e52c6e76</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//body/app-root[1]/app-dashboard-layout[1]/main[1]/app-list[1]/section[1]/app-alert-message[1]/alert[1]/div[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//body/app-root[1]/app-dashboard-layout[1]/main[1]/app-list[1]/section[1]/app-alert-message[1]/alert[1]/div[1]</value>
   </webElementProperties>
</WebElementEntity>
