<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>banner_active_hour</name>
   <tag></tag>
   <elementGuidId>ab2441f1-a9de-49d6-9b85-2d4ac0df1fa0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>body[1]/app-root[1]/app-dashboard-layout[1]/main[1]/app-create[1]/section[1]/div[1]/div[2]/form[1]/div[12]/app-time-picker[1]/timepicker[1]/table[1]/tbody[1]/tr[2]/td[1]/input[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>body[1]/app-root[1]/app-dashboard-layout[1]/main[1]/app-create[1]/section[1]/div[1]/div[2]/form[1]/div[12]/app-time-picker[1]/timepicker[1]/table[1]/tbody[1]/tr[2]/td[1]/input[1]</value>
   </webElementProperties>
</WebElementEntity>
