<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>banner_sec</name>
   <tag></tag>
   <elementGuidId>db42cc1a-45c2-4cd4-888e-72c8e696eefa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>body[1]/app-root[1]/app-dashboard-layout[1]/main[1]/app-create[1]/section[1]/div[1]/div[2]/form[1]/div[11]/app-time-picker[1]/timepicker[1]/table[1]/tbody[1]/tr[2]/td[5]/input[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>body[1]/app-root[1]/app-dashboard-layout[1]/main[1]/app-create[1]/section[1]/div[1]/div[2]/form[1]/div[11]/app-time-picker[1]/timepicker[1]/table[1]/tbody[1]/tr[2]/td[5]/input[1]</value>
   </webElementProperties>
</WebElementEntity>
