<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>coupon_clickable</name>
   <tag></tag>
   <elementGuidId>2a32713c-6b2c-4629-a6f4-a5dabd973a84</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//body/app-root[1]/app-dashboard-layout[1]/main[1]/app-edit[1]/section[1]/div[1]/div[2]/form[1]/div[6]/app-file-uploader[1]/div[2]/a[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//body/app-root[1]/app-dashboard-layout[1]/main[1]/app-edit[1]/section[1]/div[1]/div[2]/form[1]/div[6]/app-file-uploader[1]/div[2]/a[1]</value>
   </webElementProperties>
</WebElementEntity>
