<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>user_role_varifiacation</name>
   <tag></tag>
   <elementGuidId>61450f45-79fc-4652-afa5-7d370320d9e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tr//td[contains(text(),'poroshjaka+20@gmail.com')]/parent::*/following-sibling::*[1]//td[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
