<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>row</name>
   <tag></tag>
   <elementGuidId>5edee079-cf85-4765-a0b5-71e9209ed9d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//thead</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//thead</value>
   </webElementProperties>
</WebElementEntity>
