<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>header_pagination_div</name>
   <tag></tag>
   <elementGuidId>e925f3fa-3582-41fd-8b50-ff62c48f4302</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//section[@class='section']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//section[@class='section']</value>
   </webElementProperties>
</WebElementEntity>
