<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CouponImg_click</name>
   <tag></tag>
   <elementGuidId>1d78af00-37f4-40f9-bea7-ebf0ac6abfe7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//body/app-root[1]/app-dashboard-layout[1]/main[1]/app-create[1]/section[1]/div[1]/div[2]/form[1]/div[4]/app-file-uploader[1]/div[2]/a[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//body/app-root[1]/app-dashboard-layout[1]/main[1]/app-create[1]/section[1]/div[1]/div[2]/form[1]/div[4]/app-file-uploader[1]/div[2]/a[1]</value>
   </webElementProperties>
</WebElementEntity>
