<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>jpg_png-alrt_MainImg</name>
   <tag></tag>
   <elementGuidId>1a5cd688-3bf1-4a47-b9ae-e4b56a010de4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(text(),'jpg/pngファイルを選択して下さい')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(text(),'jpg/pngファイルを選択して下さい')]</value>
   </webElementProperties>
</WebElementEntity>
