<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>1_sidebar</name>
   <tag></tag>
   <elementGuidId>3d9f8cda-ae8a-4165-a0db-dda461e3816d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//app-side-bar//li[6]//a[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//app-side-bar//li[6]//a[1]</value>
   </webElementProperties>
</WebElementEntity>
